import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CitiesService {

  constructor() { }
  bigCities: string[] = [
    "Berlin, Germany",
    "Hamburg, Germany",
    "Munich, Germany",
    "Cologne, Germany",
    "Frankfurt, Germany",
    "Stuttgart, Germany",
    "Düsseldorf, Germany",
    "Dortmund, Germany",
    "Essen, Germany",
    "Leipzig, Germany",
    "Bremen, Germany",
    "Dresden, Germany",
    "Hanover, Germany",
    "Nuremberg, Germany",
    "Duisburg, Germany",
    "Bochum, Germany",
    "Wuppertal, Germany",
    "Bielefeld, Germany",
    "Bonn, Germany",
    "Münster, Germany",
    "Karlsruhe, Germany",
    "Mannheim, Germany",
    "Augsburg, Germany",
    "Wiesbaden, Germany",
    "Gelsenkirchen, Germany",
    "Mönchengladbach, Germany",
    "Braunschweig, Germany",
    "Chemnitz, Germany",
    "Kiel, Germany",
    "Aachen, Germany",
    "Halle, Germany",
    "Magdeburg, Germany",
    "Freiburg, Germany",
    "Krefeld, Germany",
    "Lübeck, Germany",
    "Oberhausen, Germany",
    "Erfurt, Germany",
    "Mainz, Germany",
    "Rostock, Germany",
    "Kassel, Germany",
    "Hagen, Germany",
    "Saarbrücken, Germany",
    "Hamm, Germany",
    "Potsdam, Germany",
    "Leverkusen, Germany",
    "Oldenburg, Germany",
    "Osnabrück, Germany",
    "Heidelberg, Germany",
    "Herne, Germany",
    "Neuss, Germany",
    "Paderborn, Germany",
    "Darmstadt, Germany",
    "Regensburg, Germany",
    "Ingolstadt, Germany",
    "Würzburg, Germany",
    "Fürth, Germany",
    "Wolfsburg, Germany",
    "Offenbach, Germany",
    "Ulm, Germany",
    "Heilbronn, Germany",
    "Pforzheim, Germany",
    "Göttingen, Germany",
    "Bottrop, Germany",
    "Recklinghausen, Germany",
    "Reutlingen, Germany",
    "Koblenz, Germany",
    "Bremerhaven, Germany",
    "Bergisch Gladbach, Germany",
    "Remscheid, Germany",
    "Jena, Germany",
    "Erlangen, Germany",
    "Moers, Germany",
    "Siegen, Germany",
    "Hildesheim, Germany",
    "Salzgitter, Germany",
    "Cottbus, Germany",
    "Gera, Germany",
    "Kaiserslautern, Germany",
    "Schwerin, Germany",
    "Gütersloh, Germany",
    "Iserlohn, Germany",
    "Zwickau, Germany",
    "Düren, Germany",
    "Esslingen am Neckar, Germany",
    "Ludwigsburg, Germany",
    "Wilhelmshaven, Germany",
    "Ratingen, Germany",
    "Trier, Germany",
    "Lünen, Germany",
    "Villingen-Schwenningen, Germany",
    "Konstanz, Germany",
    "Marl, Germany",
    "Lüneburg, Germany",
    "Flensburg, Germany",
    "Velbert, Germany",
    "Minden, Germany",
    "Viersen, Germany",
    "Dorsten, Germany",
    "Norderstedt, Germany",
    "Delmenhorst, Germany",
    "Brandenburg an der Havel, Germany",
    "Fulda, Germany",
    "Celle, Germany",
    "Rüsselsheim, Germany",
    "Worms, Germany",
    "Bergheim, Germany",
    "Nürtingen, Germany",
    "Rheine, Germany",
    "Gießen, Germany",
    "Baden-Baden, Germany",
    "Schwäbisch Gmünd, Germany",
    "Göppingen, Germany",
    "Friedrichshafen, Germany",
    "Neumünster, Germany",
    "Weimar, Germany",
    "Langenfeld (Rheinland), Germany",
    "Speyer, Germany",
    "Unna, Germany",
    "Leer, Germany",
    "Kempten (Allgäu), Germany",
    "Kerpen, Germany",
    "Troisdorf, Germany",
    "Hürth, Germany",
    "Freising, Germany",
    "Ludwigsburg, Germany",
    "Esslingen am Neckar, Germany",
    "Herrenberg, Germany",
    "Rottweil, Germany",
    "Kornwestheim, Germany",
    "Filderstadt, Germany",
    "Achim, Germany",
    "Bad Salzuflen, Germany",
    "Rüsselsheim, Germany",
    "Friedberg (Hessen), Germany",
    "Hof, Germany",
    "Dülmen, Germany",
    "Bad Homburg vor der Höhe, Germany",
    "Bietigheim-Bissingen, Germany",
    "Sindelfingen, Germany",
    "Bensheim, Germany",
    "Falkensee, Germany",
    "Stade, Germany",
    "Wedel, Germany",
    "Schorndorf, Germany",
    "Suhl, Germany",
    "Straubing, Germany",
    "Willich, Germany",
    "Schwabach, Germany",
    "Buchholz in der Nordheide, Germany",
    "Gummersbach, Germany",
    "Eisenach, Germany",
    "Idar-Oberstein, Germany",
    "Goslar, Germany",
    "Hemer, Germany",
    "Freiberg, Germany",
    "Neustadt an der Weinstraße, Germany",
    "Bad Oeynhausen, Germany",
    "Mühlhausen/Thüringen, Germany",
    "Heidenheim an der Brenz, Germany",
    "Birmingham, United Kingdom",
    "Manchester, United Kingdom",
    "Glasgow, United Kingdom",
    "Liverpool, United Kingdom",
    "Edinburgh, United Kingdom",
    "Leeds, United Kingdom",
    "Sheffield, United Kingdom",
    "Bristol, United Kingdom",
    "Cardiff, United Kingdom",
    "Marseille, France",
    "Lyon, France",
    "Toulouse, France",
    "Nice, France",
    "Nantes, France",
    "Strasbourg, France",
    "Montpellier, France",
    "Bordeaux, France",
    "Lille, France",
    "Madrid, Spain",
    "Barcelona, Spain",
    "Valencia, Spain",
    "Seville, Spain",
    "Zaragoza, Spain",
    "Málaga, Spain",
    "Murcia, Spain",
    "Palma de Mallorca, Spain",
    "Las Palmas de Gran Canaria, Spain",
    "Bilbao, Spain",
    "Rome, Italy",
    "Milan, Italy",
    "Naples, Italy",
    "Turin, Italy",
    "Palermo, Italy",
    "Genoa, Italy",
    "Bologna, Italy",
    "Florence, Italy",
    "Bari, Italy",
    "Catania, Italy",
    "Amsterdam, Netherlands",
    "Rotterdam, Netherlands",
    "The Hague, Netherlands",
    "Utrecht, Netherlands",
    "Eindhoven, Netherlands",
    "Tilburg, Netherlands",
    "Groningen, Netherlands",
    "Almere, Netherlands",
    "Breda, Netherlands",
    "Nijmegen, Netherlands",
    "Brussels, Belgium",
    "Antwerp, Belgium",
    "Ghent, Belgium",
    "Charleroi, Belgium",
    "Liège, Belgium",
    "Bruges, Belgium",
    "Namur, Belgium",
    "Leuven, Belgium",
    "Mons, Belgium",
    "Aalst, Belgium",
    "Zurich, Switzerland",
    "Geneva, Switzerland",
    "Basel, Switzerland",
    "Lausanne, Switzerland",
    "Bern, Switzerland",
    "Winterthur, Switzerland",
    "Lucerne, Switzerland",
    "St. Gallen, Switzerland",
    "Lugano, Switzerland",
    "Biel/Bienne, Switzerland",
    "Stockholm, Sweden",
    "Gothenburg, Sweden",
    "Malmö, Sweden",
    "Uppsala, Sweden",
    "Västerås, Sweden",
    "Örebro, Sweden",
    "Linköping, Sweden",
    "Helsingborg, Sweden",
    "Jönköping, Sweden",
    "Norrköping, Sweden",
    "Ottawa, Canada",
    "Montreal, Canada",
    "Oslo, Norway",
    "Bergen, Norway",
    "Trondheim, Norway",
    "Stavanger, Norway",
    "Drammen, Norway",
    "Fredrikstad, Norway",
    "Skien, Norway",
    "Kristiansand, Norway",
    "Tromsø, Norway",
    "Ålesund, Norway",
    "Copenhagen, Denmark",
    "Aarhus, Denmark",
    "Odense, Denmark",
    "Aalborg, Denmark",
    "Esbjerg, Denmark",
    "Randers, Denmark",
    "Kolding, Denmark",
    "Horsens, Denmark",
    "Vejle, Denmark",
    "Roskilde, Denmark",
    "Helsinki, Finland",
    "Espoo, Finland",
    "Tampere, Finland",
    "Vantaa, Finland",
    "Oulu, Finland",
    "Turku, Finland",
    "Jyväskylä, Finland",
    "Lahti, Finland",
    "Kuopio, Finland",
    "Pori, Finland",
    "Athens, Greece",
    "Thessaloniki, Greece",
    "Patras, Greece",
    "Heraklion, Greece",
    "Larissa, Greece",
    "Volos, Greece",
    "Rhodes, Greece",
    "Ioannina, Greece",
    "Chania, Greece",
    "Chalcis, Greece",
    "Lisbon, Portugal",
    "Porto, Portugal",
    "Vila Nova de Gaia, Portugal",
    "Amadora, Portugal",
    "Braga, Portugal",
    "Setúbal, Portugal",
    "Coimbra, Portugal",
    "Queluz, Portugal",
    "Funchal, Portugal",
    "Vila Franca de Xira, Portugal",
    "Vienna, Austria",
    "Graz, Austria",
    "Linz, Austria",
    "Salzburg, Austria",
    "Innsbruck, Austria",
    "Klagenfurt, Austria",
    "Villach, Austria",
    "Wels, Austria",
    "Sankt Pölten, Austria",
    "Dornbirn, Austria",
    "Warsaw, Poland",
    "Kraków, Poland",
    "Łódź, Poland",
    "Wrocław, Poland",
    "Poznań, Poland",
    "Gdańsk, Poland",
    "Szczecin, Poland",
    "Bydgoszcz, Poland",
    "Lublin, Poland",
    "Katowice, Poland",
    "Dublin, Ireland",
    "Cork, Ireland",
    "Limerick, Ireland",
    "Galway, Ireland",
    "Waterford, Ireland",
    "Drogheda, Ireland",
    "Dundalk, Ireland",
    "Swords, Ireland",
    "Bray, Ireland",
    "Navan, Ireland",
    "Prague, Czech Republic",
    "Brno, Czech Republic",
    "Ostrava, Czech Republic",
    "Plzeň, Czech Republic",
    "Liberec, Czech Republic",
    "Olomouc, Czech Republic",
    "Ústí nad Labem, Czech Republic",
    "Hradec Králové, Czech Republic",
    "Pardubice, Czech Republic",
    "České Budějovice, Czech Republic",
    "Budapest, Hungary",
    "Debrecen, Hungary",
    "Szeged, Hungary",
    "Miskolc, Hungary",
    "Pécs, Hungary",
    "Tokyo, Japan",
    "Delhi, India",
    "Shanghai, China",
    "São Paulo, Brazil",
    "Mumbai, India",
    "Mexico City, Mexico",
    "Beijing, China",
    "Osaka, Japan",
    "Cairo, Egypt",
    "New York City, United States",
    "Karachi, Pakistan",
    "Buenos Aires, Argentina",
    "Istanbul, Turkey",
    "Kolkata, India",
    "Manila, Philippines",
    "Lagos, Nigeria",
    "Rio de Janeiro, Brazil",
    "Dhaka, Bangladesh",
    "Bangalore, India",
    "Lima, Peru",
    "Bangkok, Thailand",
    "Ho Chi Minh City, Vietnam",
    "Los Angeles, United States",
    "Seoul, South Korea",
    "Bogotá, Colombia",
    "Chennai, India",
    "Kinshasa, Democratic Republic of the Congo",
    "Hyderabad, India",
    "Jakarta, Indonesia",
    "Lahore, Pakistan",
    "Paris, France",
    "Buenos Aires, Argentina",
    "London, United Kingdom",
    "New York City, United States",
    "Los Angeles, United States",
    "Rio de Janeiro, Brazil",
    "São Paulo, Brazil",
    "Mexico City, Mexico",
    "Manila, Philippines",
    "Karachi, Pakistan",
    "Shanghai, China",
    "Cairo, Egypt",
    "Beijing, China",
    "Bogotá, Colombia",
    "Lima, Peru",
    "Buenos Aires, Argentina",
    "Bangkok, Thailand",
    "Delhi, India",
    "Guangzhou, China",
    "Seoul, South Korea",
    "Jakarta, Indonesia",
    "Tokyo, Japan",
    "Kinshasa, Democratic Republic of the Congo",
    "Lagos, Nigeria",
    "Istanbul, Turkey",
    "Shenzhen, China",
    "Dongguan, China",
    "Kolkata, India",
    "Cairo, Egypt",
    "Mumbai, India",
    "Mexico City, Mexico",
    "Lahore, Pakistan",
    "Bangalore, India",
    "Bogotá, Colombia",
    "Buenos Aires, Argentina",
    "New York City, United States",
    "São Paulo, Brazil",
    "Los Angeles, United States",
    "Delhi, India",
    "Moscow, Russia",
    "Jakarta, Indonesia",
    "Karachi, Pakistan",
    "Cairo, Egypt",
    "Mumbai, India",
    "Seoul, South Korea",
    "Shanghai, China",
    "Lagos, Nigeria",
    "Istanbul, Turkey",
    "Bangkok, Thailand",
    "Beijing, China",
    "Karachi, Pakistan",
    "Buenos Aires, Argentina",
    "Dhaka, Bangladesh",
    "Delhi, India",
    "Istanbul, Turkey",
    "Tokyo, Japan",
    "Mumbai, India",
    "Beijing, China",
    "São Paulo, Brazil",
    "Shenzhen, China",
    "Lagos, Nigeria",
    "Dhaka, Bangladesh",
    "Seoul, South Korea",
    "Guangzhou, China",
    "Shanghai, China",
    "Rio de Janeiro, Brazil",
    "Lahore, Pakistan",
    "Bangalore, India",
    "Kinshasa, Democratic Republic of the Congo",
    "Tianjin, China",
    "Chennai, India",
    "Bogotá, Colombia",
    "Bangkok, Thailand",
    "Lima, Peru",
    "Nanjing, China",
    "Ho Chi Minh City, Vietnam",
    "Hong Kong, China",
    "Foshan, China",
    "Hyderabad, India",
    "Linyi, China",
    "Wuhan, China",
    "Hangzhou, China",
    "Chengdu, China",
    "Tongshan, China",
    "Ahmedabad, India",
    "Chongqing, China",
    "Kuala Lumpur, Malaysia",
    "Luanda, Angola",
    "Nairobi, Kenya",
    "Tehran, Iran",
    "Johannesburg, South Africa",
    "Casablanca, Morocco",
    "Dar es Salaam, Tanzania",
    "Alexandria, Egypt",
    "Abidjan, Ivory Coast",
    "Khartoum, Sudan",
    "Maputo, Mozambique",
    "Bamako, Mali",
    "Lubumbashi, Democratic Republic of the Congo",
    "Libreville, Gabon",
    "Dakar, Senegal",
    "Kano, Nigeria",
    "Algiers, Algeria",
    "Accra, Ghana",
    "Addis Ababa, Ethiopia",
    "Douala, Cameroon",
    "Luanda, Angola",
    "Lusaka, Zambia",
    "Harare, Zimbabwe",
    "Mombasa, Kenya",
    "Brazzaville, Congo",
    "Antananarivo, Madagascar",
    "Yaoundé, Cameroon",
    "Gaborone, Botswana",
    "Maseru, Lesotho",
    "Lilongwe, Malawi",
    "N'Djamena, Chad",
    "Nouakchott, Mauritania",
    "Porto-Novo, Benin",
    "Windhoek, Namibia",
    "Ouagadougou, Burkina Faso",
    "Bissau, Guinea-Bissau",
    "Conakry, Guinea",
    "Kigali, Rwanda",
    "Bujumbura, Burundi",
    "Malabo, Equatorial Guinea",
    "Banjul, Gambia",
    "Freetown, Sierra Leone",
    "Monrovia, Liberia",
    "Victoria, Seychelles",
    "Moroni, Comoros",
    "Asmara, Eritrea",
    "Bridgetown, Barbados",
    "Kingstown, Saint Vincent and the Grenadines",
    "Saint George's, Grenada",
    "Castries, Saint Lucia",
    "Basseterre, Saint Kitts and Nevis",
    "Roseau, Dominica",
    "Port-au-Prince, Haiti",
    "Nassau, Bahamas",
    "Kingston, Jamaica",
    "Havana, Cuba",
    "Santo Domingo, Dominican Republic",
    "San Juan, Puerto Rico",
    "Belize City, Belize",
    "Saint John's, Antigua and Barbuda",
    "Basseterre, Saint Kitts and Nevis",
    "Roseau, Dominica",
    "Castries, Saint Lucia",
    "Saint George's, Grenada",
    "Kingstown, Saint Vincent and the Grenadines",
    "Port of Spain, Trinidad and Tobago",
    "St. John's, Antigua and Barbuda",
    "Basseterre, Saint Kitts and Nevis",
    "Roseau, Dominica",
    "Castries, Saint Lucia",
    "Saint George's, Grenada",
    "Kingstown, Saint Vincent and the Grenadines",
    "Port of Spain, Trinidad and Tobago",
    "Gustavia, Saint Barthélemy",
    "Marigot, Saint Martin",
    "Cockburn Town, Turks and Caicos Islands",
    "The Valley, Anguilla",
    "Basse-Terre, Guadeloupe",
    "Plymouth, Montserrat",
    "Hamilton, Bermuda",
    "Charlotte Amalie, U.S. Virgin Islands",
    "George Town, Cayman Islands",
    "Oranjestad, Aruba",
    "Philipsburg, Sint Maarten",
    "Willemstad, Curaçao",
    "Road Town, British Virgin Islands",
    "Saint-Pierre, Saint Pierre and Miquelon",
    "Fort-de-France, Martinique",
    "Bridgetown, Barbados",
    "Kingstown, Saint Vincent and the Grenadines",
    "Castries, Saint Lucia",
    "Roseau, Dominica",
    "Basseterre, Saint Kitts and Nevis",
    "Saint George's, Grenada",
    "Gustavia, Saint Barthélemy",
    "Marigot, Saint Martin",
    "Cockburn Town, Turks and Caicos Islands",
    "The Valley, Anguilla",
    "Basse-Terre, Guadeloupe",
    "Plymouth, Montserrat",
    "Hamilton, Bermuda",
    "Charlotte Amalie, U.S. Virgin Islands",
    "George Town, Cayman Islands",
    "Oranjestad, Aruba",
    "Philipsburg, Sint Maarten",
    "Willemstad, Curaçao",
    "Road Town, British Virgin Islands",
    "Saint-Pierre, Saint Pierre and Miquelon",
    "Fort-de-France, Martinique",
    "Bridgetown, Barbados",
    "Nassau, Bahamas",
    "Kingston, Jamaica",
    "Port-au-Prince, Haiti",
    "Havana, Cuba",
    "Santo Domingo, Dominican Republic",
    "San Juan, Puerto Rico",
    "Santiago, Chile",
    "Guayaquil, Ecuador",
    "Caracas, Venezuela",
    "Manaus, Brazil",
    "Montevideo, Uruguay",
    "Porto Alegre, Brazil",
    "Santiago, Dominican Republic",
    "Curitiba, Brazil",
    "Recife, Brazil",
    "Santa Cruz, Bolivia",
    "Córdoba, Argentina",
    "Rosario, Argentina",
    "Valparaíso, Chile",
    "Maracaibo, Venezuela",
    "Iquitos, Peru",
    "La Paz, Bolivia",
    "Barranquilla, Colombia",
    "Antofagasta, Chile",
    "Salta, Argentina",
    "Jujuy, Argentina",
    "Concepción, Chile",
    "Barquisimeto, Venezuela",
    "Viña del Mar, Chile",
    "Temuco, Chile",
    "Manizales, Colombia",
    "Punta Arenas, Chile",
    "Osorno, Chile",
    "Arica, Chile",
    "Calama, Chile",
    "Iquique, Chile",
    "Copiapó, Chile",
    "Rancagua, Chile",
    "Talca, Chile",
    "Los Ángeles, Chile",
    "Temuco, Chile",
    "Valdivia, Chile",
    "Puerto Montt, Chile",
    "Coyhaique, Chile",
    "Puerto Aysén, Chile",
    "Punta Arenas, Chile",
    "Arica, Chile",
    "Calama, Chile",
    "Valparaíso, Chile",
    "Viña del Mar, Chile",
    "Temuco, Chile",
    "Manizales, Colombia",
    "Punta Arenas, Chile",
    "Osorno, Chile",
    "Arica, Chile",
    "Calama, Chile",
    "Iquique, Chile",
    "Copiapó, Chile",
    "Rancagua, Chile",
    "Talca, Chile",
    "Los Ángeles, Chile",
    "Temuco, Chile",
    "Valdivia, Chile",
    "Puerto Montt, Chile",
    "Coyhaique, Chile",
    "Puerto Aysén, Chile",
    "Punta Arenas, Chile",
    "Iquique, Chile",
    "Arica, Chile",
    "San Carlos de Bariloche, Argentina",
    "Esquel, Argentina",
    "Tarija, Bolivia",
    "Tupiza, Bolivia",
    "Villazón, Bolivia",
    "Oruro, Bolivia",
    "Potosí, Bolivia",
    "Sucre, Bolivia",
    "Cochabamba, Bolivia",
    "Samaipata, Bolivia",
    "Santa Cruz de la Sierra, Bolivia",
    "Tarija, Bolivia",
    "Tupiza, Bolivia",
    "Villazón, Bolivia",
    "Oruro, Bolivia",
    "Potosí, Bolivia",
    "Sucre, Bolivia",
    "Cochabamba, Bolivia",
    "Samaipata, Bolivia",
    "Santa Cruz de la Sierra, Bolivia",
    "Copacabana, Bolivia",
    "Coroico, Bolivia",
    "La Paz, Bolivia",
    "Rurrenabaque, Bolivia",
    "San Ignacio de Velasco, Bolivia",
    "San José de Chiquitos, Bolivia",
    "San Matías, Bolivia",
    "Tarija, Bolivia",
    "Tupiza, Bolivia",
    "Villazón, Bolivia",
    "Oruro, Bolivia",
    "Potosí, Bolivia",
    "Sucre, Bolivia",
    "Cochabamba, Bolivia",
    "Samaipata, Bolivia",
    "Santa Cruz de la Sierra, Bolivia",
    "Copacabana, Bolivia",
    "Coroico, Bolivia",
    "La Paz, Bolivia",
    "Rurrenabaque, Bolivia",
    "San Ignacio de Velasco, Bolivia",
    "San José de Chiquitos, Bolivia",
    "San Matías, Bolivia",
    "Tarija, Bolivia"
  ]

}
